# Generated by Django 6.1 on 2026-09-02 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baccalaureat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('Classement', 'Classement'), ('Concours', 'Concours')], max_length=50)),
                ('bourse', models.PositiveIntegerField()),
                ('secour', models.PositiveIntegerField()),
                ('deboucher', models.TextField()),
                ('bac', models.ManyToManyField(related_name='bac', to='orientations.baccalaureat')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='orientations.etablissement')),
                ('matiere', models.ManyToManyField(related_name='matiere', to='orientations.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='etablissement',
            name='Universite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='orientations.universite'),
        ),
    ]
