# Generated by Django 6.1 on 2026-09-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField()),
                ('bac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='orientations.baccalaureat')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='orientations.matiere')),
            ],
            options={
                'unique_together': {('matiere', 'bac')},
            },
        ),
    ]
