# Generated by Django 6.1 on 2026-09-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='utilisateur',
        ),
    ]
